## Support and terms of service

Posit does not provide support or assistance for any code written or generated in Positron, with or without AI features in Positron such as Posit Assistant, Positron Assistant, or Databot, regardless of which model provider you use. Posit does not support any model provider's output or test the logic a provider uses to generate code from prompts. Consult your AI model provider's [documentation](assistant-provider-info.qmd) for more information.

### BYO-key model providers

AI features in Positron use a bring-your-own-key (BYO-key) model. You connect to a range of different model providers, such as Anthropic, Amazon Bedrock, GitHub Copilot, or OpenAI. You or your organization has an agreement with the provider and pays them directly for access to the model.

### Data collection and privacy

Positron provides local software as a client to your selected model provider. As a result, Posit does not track, collect, or store your prompts, code, or conversations when you use AI features within Positron (i.e., Posit Assistant, Positron Assistant, Databot, etc.). This applies as long as you use an external model provider. These features operate by communicating directly from your client software to your chosen AI model provider. Posit does not receive any AI traffic from your client's software and nor does Posit ever access or store your data. If you select [Posit AI](assistant-provider-info.qmd#posit-ai) as your model provider, the [[privacy policy](privacy.qmd)]{.content-visible when-profile="positron"}[[privacy policy](https://posit.co/about/privacy-policy/)]{.content-visible when-profile="workbench"} and [Posit AI Agreement](https://posit.co/about/posit-ai-agreement) apply instead.

If you voluntarily share diagnostic logs or information with Posit for troubleshooting purposes, that shared information will be handled in accordance with [[Posit's privacy policy](privacy.qmd)]{.content-visible when-profile="positron"}[[Posit's privacy policy](https://posit.co/about/privacy-policy/)]{.content-visible when-profile="workbench"}.

However, your AI model provider may store or collect data according to their own privacy policies and terms of service. Please review your [AI model provider's data practices](assistant-provider-info.qmd) for details on what information they collect and how it is used.

By using an external model provider, you acknowledge that your use is subject to their Terms of Service. All external model providers are considered “Third Party Materials” as defined in the [Posit End User License Agreement](https://posit.co/about/eula/) and Posit assumes no liability or other obligations with respect thereto and, without limiting the foregoing, is not liable for any loss or damage resulting from the use or access thereof.
