project:
  title: "Positron"
  type: posit-docs
  render:
    - "*.qmd"

execute:
  freeze: auto

website:
  favicon: "images/favicon.svg"
  repo-url: https://github.com/posit-dev/positron-website
  issue-url: https://github.com/posit-dev/positron/issues/
  repo-actions: [edit, source, issue]
  page-footer:
    left: |
      Copyright &copy; 2022-2025 Posit Software, PBC. All Rights Reserved.
    center: "Positron {{< env RELEASE_VERSION >}}"
    right:
      - text: "License"
        href: licensing.qmd
      - text: "Privacy Policy"
        aria-label: "Link to Privacy Policy"
        href: "https://posit.co/about/privacy-policy/"
      - icon: question-circle-fill
        aria-label: 'Link to Posit Support'
        href: "https://support.posit.co/hc/en-us"
      - icon: lightbulb-fill
        aria-label: 'Link to Posit Solutions'
        href: "https://solutions.posit.co/"
      - text: "<img alt='Link to Posit Documentation' src='images/posit-guide-ltmd.svg' id='footer-right-logo'>"
        href: "https://docs.posit.co/"
      - text: "<img alt='Link to main Posit site' src='images/posit-icon-fullcolor.svg' id='footer-right-posit-logo'>"
        href: "https://posit.co/"
  navbar:
    left:
      - text: "Get Started"
        href: start.qmd
      - text: "Guides"
        href: add-to-path.qmd
      - text: "Help"
        href: troubleshooting.qmd
      - text: "<span class='btn btn-primary'>Download</span>"
        href: download.qmd
    right:
      - icon: github
        aria-label: 'Link to Positron Github Repository'
        href: https://github.com/posit-dev/positron

  sidebar:
    - title: "Get Started"
      style: "docked"
      contents:
        - start.qmd
        - download.qmd
        - extensions.qmd
        - about.qmd

    - title: "Guides"
      style: "docked"
      contents:
        - add-to-path.qmd
        - section: "Interpreters"
          contents:
            - managing-interpreters.qmd
            - interpreter-startup.qmd
            - python-installations.qmd
            - r-installations.qmd
        - action-bars.qmd
        - keyboard-shortcuts.qmd
        - data-explorer.qmd
        - assistant.qmd
        - connections-pane.qmd
        - help-pane.qmd
        - run-interactive-apps.qmd
        - jupyter-notebooks.qmd
        - remote-ssh.qmd
        - updating.qmd
        - extension-development.qmd
        - folder-templates.qmd
        - text: "Migrating from VS Code"
          href: migrate-vscode.qmd
        - section: "Migrating from RStudio"
          contents:
          - rstudio-keybindings.qmd
          - rstudio-rproj-file.qmd
          - r-snippets.qmd
        - git.qmd
    - title: "Help"
      style: "docked"
      contents:
        - troubleshooting.qmd
        - feedback.qmd
        - faqs.qmd
        - privacy.qmd

format:
  html:
    css: styles.css
