project:
  title: "Positron"
  type: posit-docs
  render:
    - "*.qmd"

execute:
  freeze: auto

website:
  favicon: "images/favicon.svg"
  site-url: https://positron.posit.co
  repo-url: https://github.com/posit-dev/positron-website
  issue-url: https://github.com/posit-dev/positron/issues/
  repo-actions: [edit, source, issue]
  page-footer:
    left:
      - text: "<img class='posit-footer-logo' alt='Posit' src='images/posit-logo-black-TM.svg'>Copyright &copy; 2022-2025 Posit Software, PBC. All Rights Reserved."
        href: "https://posit.co/"
    center: "Positron {{< env RELEASE_VERSION >}}"
    right:
      - text: "Support"
        href: "https://support.posit.co/"
      - text: "License"
        href: licensing.qmd
      - text: "Privacy Policy"
        aria-label: "Link to Privacy Policy"
        href: "https://posit.co/about/privacy-policy/"

  navbar:
    left:
      - text: "Features"
        href: features.qmd
      - text: "Guides"
        href: welcome.qmd
      - text: "Help"
        href: troubleshooting.qmd
      - text: "About"
        href: about.qmd  
      - text: "<span id='top-bar-download-btn' class='btn btn-primary'>Download</span>"
        href: download.qmd        
      
    right:
      - icon: github
        aria-label: 'Link to Positron Github Repository'
        href: https://github.com/posit-dev/positron
      
  sidebar:
    - title: "Features"
      style: "docked"
      contents:
        - features.qmd
        - section: "AI Tools"
          contents:
          - assistant.qmd
          - databot.qmd
        - section: "Exploratory Data Analysis"
          contents:
            - data-explorer.qmd  
            - variables-pane.qmd
        - section: "Dynamic Documents and Apps"
          contents:
            - quarto.qmd
            - jupyter-notebooks.qmd
            - develop-data-apps.qmd
        - help-pane.qmd    
        - folder-templates.qmd
        - remote-ssh.qmd
        - section: "Database Connections"
          contents:
            - connections-pane.qmd
            - extending-connections.qmd 
  
    - title: "Guides"
      style: "docked"
      contents:
        - section: "Getting Started"
          contents:
            - welcome.qmd
            - install.qmd
            - download.qmd
            - extensions.qmd
            - updating.qmd
            - keyboard-shortcuts.qmd
            - add-to-path.qmd
            - git.qmd
        - section: "User Interface"
          contents:
            - layout.qmd
            - command-palette.qmd
            - action-bars.qmd
        - section: "Interpreters"
          contents:
            - managing-interpreters.qmd
            - interpreter-startup.qmd
            - python-installations.qmd
            - r-installations.qmd
            - reticulate.qmd
        - text: "Migrating from VS Code"
          href: migrate-vscode.qmd
        - section: "Migrating from RStudio"
          contents:
          - migrate-rstudio.qmd
          - migrate-rstudio-keybindings.qmd
          - migrate-rstudio-settings-and-extensions.qmd
          - migrate-rstudio-code.qmd
          - migrate-rstudio-rproj.qmd
          - migrate-rstudio-compare.qmd
        - section: "Extending Positron"  
          contents:
          - extension-development.qmd
    - title: "Help"
      style: "docked"
      contents:
        - troubleshooting.qmd
        - feedback.qmd
    - title: "About"
      style: "docked"
      contents:
        - about.qmd
        - privacy.qmd
        - faqs.qmd    
    

format:
  html:
    css: css/styles.css
    mermaid: 
      theme: neutral
    link-external-filter: '^(?:http:|https:)\/\/(?:positron|cdn)\.posit\.co(?:\/|$)|^(?:http:|https:)\/\/.*--positron-posit-co\.netlify\.app(?:\/|$)|^(?!https?:\/\/)'
