---
title: "Download Positron"
params:
  version: "2025.06.0-167"
format:
  html:
    include-in-header:
      - '_download.html'

---

### Positron on desktop

Find out what you need to know to [get started](start.qmd) using Positron, then download the desktop installer for your platform.

::: callout-important
## Accept license agreement

Please review [Positron's license agreement](licensing.qmd) and [privacy policy](https://posit.co/about/privacy-policy/). Your acceptance of this license agreement and privacy policy is required as a condition to proceeding with your download or use of the software.

<div id="privacy-policy-agreement">
  <input type="checkbox" id="privacy-checkbox" onclick="updatePrivacy(this)">
  <label>I agree to the [Positron license agreement](licensing.qmd) and [Posit Privacy Policy](https://posit.co/about/privacy-policy/).</label>
</div>
:::


```{r, id='download-table'}
#| echo: false
#| classes: plain

library(purrr)
library(glue)
library(httr)
library(jsonlite, warn.conflicts = FALSE) # conflict with purrr::flatten

cdn_url <- "https://cdn.posit.co/positron/prereleases/"

urls <- list(
  glue("{cdn_url}win/x86_64/Positron-{params$version}-Setup.exe"),
  glue("{cdn_url}win/x86_64/Positron-{params$version}-UserSetup.exe"),
  glue("{cdn_url}mac/universal/Positron-{params$version}.dmg"),
  glue("{cdn_url}deb/x86_64/Positron-{params$version}-x64.deb"),
  glue("{cdn_url}deb/arm64/Positron-{params$version}-arm64.deb"),
  glue("{cdn_url}rpm/x86_64/Positron-{params$version}-x64.rpm"),
  glue("{cdn_url}rpm/arm64/Positron-{params$version}-arm64.rpm")
)

cloudfront_headers <- map(urls, HEAD) |> map(headers)

# Read JSON file
checksum_data <- rlang::try_fetch(
  fromJSON(glue("{cdn_url}positron-{params$version}-checksums.json")), 
  error = function(cnd) list(),
  warning = function(cnd) list()
)

# Create checksums array in the correct order
checksums <- list(
  full = c(
    checksum_data$win_system,      # Windows system level
    checksum_data$win_user,        # Windows user level
    checksum_data$mac,             # MacOS universal
    checksum_data$linux_deb_x64,   # Debian x64
    checksum_data$linux_deb_arm64, # Debian arm64
    checksum_data$linux_rpm_x64,   # Red Hat x64
    checksum_data$linux_rpm_arm64  # Red Hat arm64
  ),
  short = substr(c(
    checksum_data$win_system,      # Windows system level
    checksum_data$win_user,        # Windows user level
    checksum_data$mac,             # MacOS universal
    checksum_data$linux_deb_x64,   # Debian x64
    checksum_data$linux_deb_arm64, # Debian arm64
    checksum_data$linux_rpm_x64,   # Red Hat x64
    checksum_data$linux_rpm_arm64  # Red Hat arm64
  ), 1, 7)
)

file_sizes <- map(cloudfront_headers, "content-length") |>
  map(fs::fs_bytes) |>
  map_chr(as.character)
file_names_only <- stringr::str_extract(urls, "[^\\/]+$")

markdown_links <- glue('<a href="{urls}">{file_names_only}</a>')

# Create base table without checksums
download_table <- data.frame(
  Platform = c(
    "Windows 10, 11 x64 (system level install)",
    "Windows 10, 11 x64 (user level install)",
    "MacOS 10.15+ (universal)",
    "Debian-based Linux x64 (Ubuntu 20+)",
    "Debian-based Linux arm64 (Ubuntu 20+)",
    "Red Hat-based Linux x64 (RHEL9)",
    "Red Hat-based Linux arm64 (RHEL9)"
  ),
  Download = markdown_links,
  Size = file_sizes
)

# Add checksums column if data is available
if (length(checksums$full) > 0) {
  download_table$`SHA-256` <- sprintf(
    '<span class="checksum" onclick="copyChecksum(\'%s\', this)" title="Click to copy full checksum">%s</span>', 
    checksums$full, 
    checksums$short
  )
}

knitr::kable(download_table, format = "html", escape = FALSE)
```
<br>
Older releases [are available on GitHub](https://github.com/posit-dev/positron/releases).

### Positron Pro on Posit Workbench

[Posit Workbench](https://posit.co/products/enterprise/workbench/) 2024.12.1 and later includes preview support for Positron Pro. To configure and use Positron Pro on Posit Workbench, please see the [Posit Workbench Administration Guide](https://docs.posit.co/ide/server-pro/positron_sessions/) and the [Positron Pro user guide](https://docs.posit.co/ide/server-pro/user/positron/getting-started/).
