---
title: "Install Positron"
description: "Get started with Positron right away. Install the free data science IDE for Python and R, with prerequisites and setup instructions for all platforms."
format:
  html:
    include-in-header:
      - '_download.html'
aliases:
  - start.html
---

Positron is a modern, extensible IDE for data science built on [Code OSS](https://github.com/microsoft/vscode). Before you install Positron, please review the prerequisites below to ensure your system is ready.

## Prerequisites
::: {.panel-tabset}

### Windows

If you're using Windows, make sure you have the [latest Visual C++ Redistributable](https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#latest-microsoft-visual-c-redistributable-version) installed.

### Python setup
Positron works with [actively supported versions](https://devguide.python.org/versions/#versions) of Python, from 3.9 to 3.13.

We recommend [uv](https://docs.astral.sh/uv/guides/install-python/), or [pyenv](https://github.com/pyenv/pyenv) and [pyenv for Windows](https://github.com/pyenv-win/pyenv-win), for managing Python versions.

Positron requires the [IPython kernel](https://pypi.org/project/ipykernel/) (version 6.19.1 or higher) to communicate with Python. By default, the IPython kernel is bundled with Positron for the CPython implementation (the standard Python implementation) and added to the [Python search path](https://docs.python.org/3/library/sys_path_init.html).

If you prefer finer control over your Python environment, set the [`python.useBundledIpykernel`](positron://settings/python.useBundledIpykernel) setting to false and install the IPython kernel manually

::: callout-note
If you're using an implementation other than CPython, you'll need to install the IPython kernel manually.
:::

### R setup

If you plan to use R with Positron, ensure you have R 4.2 or higher installed. To install R, follow the instructions for your operating system at <https://cloud.r-project.org/>.

Alternatively, if you'd like to have multiple R installations, [rig](https://github.com/r-lib/rig) is a great tool to manage this which works well with Positron.

If you're an R package developer, you will also want to make sure that you have the current versions of certain R packages, all of which had recent updates to make them work more smoothly in Positron. Run one of the code snippets below to ensure that you are up-to-date:

``` r
# if you're a pak person (we are!)
pak::pak(c("usethis", "cli", "crayon", "rlang", "roxygen2", "pkgload"))

# or using base R
install.packages(c("usethis", "cli", "crayon", "rlang", "roxygen2", "pkgload"))
```

::: callout-note
If you're a Windows user, note that Positron doesn't currently bundle [Rtools](https://cran.r-project.org/bin/windows/Rtools/). If you need Rtools for your package development or other work, you can either use the official guidance from CRAN on installing Rtools and putting it on the PATH, or alternatively, use [rig](https://github.com/r-lib/rig) to install and set up Rtools:

```bash
rig system rtools add
```
:::

:::

## Install Positron

Download the installer for your operating system from the button below and follow the standard installation process for your platform. You only need to install Positron once, as it [automatically updates](updating.qmd) to the latest version after installation.

:::{.callout-important #privacy-policy}
## Accept license agreement

Please review [Positron's license agreement](licensing.qmd) and [privacy policy](https://posit.co/about/privacy-policy/). Your acceptance of this license agreement and privacy policy is required as a condition to proceeding with your download or use of the software.

<div id="privacy-policy-agreement">
  <input type="checkbox" id="privacy-checkbox" onclick="updatePrivacy(this)">
  <label>I agree to the <a href="licensing.qmd">Positron license agreement</a> and <a href="https://posit.co/about/privacy-policy/">Posit Privacy Policy</a>.</label>
</div>
:::

<!-- The below R code is used by the _download.html snippet
to populate the platform-default download button -->
```{r}
#| echo: false
positronVersion <- Sys.getenv("RELEASE_VERSION")
```

[Download Positron <span id="os-name"></span>](#){.btn .btn-primary .disabled #download-btn data-version="`{r} positronVersion`"}

[All Downloads](download.qmd){#all-downloads}
