---
title: "Navigation"
---

This guide helps RStudio users adapt to Positron's methods for navigating through source code.

*Based on converting everything I see here: <https://docs.posit.co/ide/user/ide/guide/code/code-navigation.html>*

| Navigation Task | RStudio | Closest equivalent in Positron |
| --------------- | ------- | -------- |
| Find in Files | <kbd>Ctrl/Cmd</kbd>+<kbd>Shift</kbd>+<kbd>F</kbd> | <kbd>Ctrl/Cmd</kbd>+<kbd>Shift</kbd>+<kbd>F</kbd> <br> [Search across files](https://code.visualstudio.com/docs/editor/codebasics#_search-across-files) |
| Go to File | <kbd>Ctrl/Cmd</kbd>+<kbd>.</kbd> | <kbd>Ctrl/Cmd</kbd>+<kbd>P</kbd> <br> [Quick open](https://code.visualstudio.com/docs/editing/editingevolved#_quick-file-navigation)|
| Go to Function/Symbol | <kbd>Ctrl/Cmd</kbd>+<kbd>.</kbd> | With RStudio keybindings enabled: <br> <kbd>Ctrl/Cmd</kbd>+<kbd>.</kbd><br><br>Available in all configurations: <br> <kbd>Ctrl/Cmd</kbd>+<kbd>T</kbd> <br>[Go to Symbol in Workspace](https://code.visualstudio.com/docs/editor/editingevolved#_go-to-symbol)<br><br><kbd>Ctrl/Cmd</kbd>+<kbd>Shift</kbd>+<kbd>O</kbd> (symbols in current file) |
| Go to Function Definition | <kbd>F2</kbd> or <kbd>Ctrl/Cmd</kbd> + click | <kbd>F2</kbd> <br><br> With RStudio keybindings enabled: <br> <kbd>Ctrl/Cmd</kbd> + click |
| Jump to Line | <kbd>Alt/Option</kbd>+<kbd>Shift</kbd>+<kbd>G</kbd> | <kbd>Ctrl</kbd>+<kbd>G</kbd> |
| Navigate Back or Forward | <kbd>Ctrl/Cmd</kbd>+<kbd>F9</kbd> <br> <kbd>Ctrl/Cmd</kbd>+<kbd>F10</kbd> | Windows/Linux: <br> <kbd>Alt</kbd>+<kbd>Left</kbd><br> <kbd>Alt</kbd>+<kbd>Right</kbd> <br><br> Mac: <br> <kbd>Ctrl</kbd>+<kbd>-</kbd> <br> <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>-</kbd> |
| Focus Previous or Next Editor Tab | <kbd>Ctrl/Cmd</kbd>+<kbd>Alt</kbd>+<kbd>Left</kbd> <br> <kbd>Ctrl/Cmd</kbd>+<kbd>Alt</kbd>+<kbd>Right</kbd> | With RStudio keybindings enabled: <br> <kbd>Ctrl/Cmd</kbd>+<kbd>Alt</kbd>+<kbd>Left</kbd> <br> <kbd>Ctrl/Cmd</kbd>+<kbd>Alt</kbd>+<kbd>Right</kbd> |

*TO DISCUSS: say anything about the outline? Or breadcrumbs? This feels like an active area of folks asking questions and opening issues, based on some friction in their RStudio to Positron migration journey.*
