---
title: "RStudio Migration Overview"
---

We expect that many existing RStudio users are curious about Positron and whether they should take it for a test drive or even make it their primary IDE.
This overview and several detailed subtopics should help RStudio users feel well-informed about what such a transition would feel like.
The goal is to give RStudio users the smoothest possible experience in their early days with Positron.

First, be assured that RStudio is not going away.
RStudio is still actively supported and there are no concrete plans to sunset it.
That being said, RStudio and Positron are at very different points in their respective lifecycles, which is relevant when making decisions about adoption.
Positron is under much more active development, with a rapidly expanding set of features.
RStudio's development, on the other hand, is much more focused on bug fixes and product stability.

Here are some features that are present in RStudio, but not in Positron.
Some of these features may eventually come to Positron, but if any of these are dealbreakers for you, that is a reason to stick with RStudio.

* Inline output in Quarto documents, i.e. a notebook-style interface for `.qmd` (or `.Rmd`) files. Tracked in <https://github.com/posit-dev/positron/issues/5640>.
* Something about R Markdown? Relevant issue: <https://github.com/posit-dev/positron/issues/1421>.
* Saving and re-loading workspace state when you restart R.
* Dedicated panes and buttons for specialized tasks, such code profiling or installing or developing packages.
* History pane. Tracked in <https://github.com/posit-dev/positron/issues/5484>.
* Data import widget.
* RStudio add-ins. Tracked in <https://github.com/posit-dev/positron/issues/1313>.

Here are features that are present in Positron, but not in RStudio.
If any of these features are very appealing to you, that is a reason to move some or perhaps all of your work to Positron.

* Easy access to [multiple R versions](r-installations.qmd) and [multiple concurrent R sessions](managing-interpreters.qmd).
* An [integrated AI assistant](assistant.qmd) that can "see" and, optionally, execute code in your active R (or Python) sessions, among many other capabilities.
* Python as a first-class citizen, with support for data science workflows that is on par with R.
* Support for other languages beyond R and Python, via built-in language intelligence or extensions.
* An integrated [data explorer](data-explorer.qmd) for dataframes in your active R (or Python) sessions and for a variety data files (CSV, Parquet, etc.).
* Extensibility via a large marketplace of 3rd party [extensions](extensions.qmd).
* [Remote sessions](remote-ssh.qmd), i.e. where the user interface is local but the compute is elsewhere.

It's also worth pointing out that using Positron is not an all-or-nothing decision.
It is entirely reasonable to use Positron in some projects and RStudio in others.
Likewise, within a specific project, some tasks might feel easier in Positron and others in RStudio.
There is nothing irreversible or exclusive about interacting with the files that constitute a project from one IDE versus another.

## Command Palette

One overarching difference between RStudio and Positron (and VS Code) is the importance of the **command palette**.
While RStudio offers a command palette, it was a relatively late addition to the interface and many users never got into the habit of using it.
Instead RStudio users are accustomed to many specialized buttons, panes, and menus.

Positron leans much more heavily on the command palette, which is inherited from VS Code.
When you find yourself thinking "I want to do X in Positron" - whether that's running code, rendering a document, or configuring a setting - try making the command palette your first stop.

### Using the Command Palette

To open the Command Palette, press <kbd>Ctrl/Cmd</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd>.
Start typing a keyword or the name of a command and the fuzzy finder will start to display matches.
Use the arrow keys to select a command, then press <kbd>Enter</kbd> to run it.

*TODO: conclude the overview with a bullet list of the more specialized topics? Or is that just redundant to what's in the sidebar?*
