---
title: "RStudio Keybindings"
---

<!-- vale Posit.Contractions = NO -->

## RStudio keybindings in Positron

If you'd prefer to use RStudio keybindings in Positron, enable the [`workbench.keybindings.rstudioKeybindings` setting](positron://settings/workbench.keybindings.rstudioKeybindings). Restart Positron after changing this setting.

The following RStudio keybindings will then be enabled:

| Shortcut | Description |
| -------- | ----------- |
| {{< kbd Ctrl-1 >}}  |  Focus Source |
| {{< kbd Ctrl-2 >}}  |  Focus Console |
| {{< kbd mac=Command-. win=Ctrl-. linux=Ctrl-. >}}  |  Go to Symbol |
| {{< kbd mac=Command-Shift-C win=Ctrl-Shift-C linux=Ctrl-Shift-C >}} |  Comment/Uncomment a line |
| {{< kbd mac=Command-Shift-N win=Ctrl-Shift-N linux=Ctrl-Shift-N >}} |  Create a new R file |
| {{< kbd F2 >}} |  Go to definition |
| {{< kbd mac=Command-I win=Ctrl-I linux=Ctrl-I >}} |  Reindent selection |
| {{< kbd mac=Command-Shift-A win=Ctrl-Shift-A linux=Ctrl-Shift-A >}} |  Reformat selection |
| {{< kbd mac=Command-Shift-S win=Ctrl-Shift-S linux=Ctrl-Shift-S >}} |  Source the current R script |
| {{< kbd mac=Command-Option-Shift-M win=Ctrl-Alt-Shift-M linux=Ctrl-Alt-Shift-M >}} |  Rename |
| {{< kbd mac=Command-Option-I win=Ctrl-Alt-I linux=Ctrl-Alt-I >}} |  Insert a new Quarto/R Markdown cell |
| {{< kbd mac=Command-Option-M win=Ctrl-Alt-M linux=Ctrl-Alt-M >}} |  Open version control pane |
| {{< kbd mac=Command-Option-Left win=Ctrl-Alt-Left linux=Ctrl-Alt-Left >}} |  Go to previous tab |
| {{< kbd mac=Command-Option-Right win=Ctrl-Alt-Right linux=Ctrl-Alt-Right >}} |  Go to next tab |
| {{< kbd mac=Command-D win=Ctrl-D linux=Ctrl-D >}} |  Delete the current line |
| {{< kbd mac=Command-Shift-M win=Ctrl-Shift-M linux=Ctrl-Shift-M >}} |  Insert pipe operator |
| {{< kbd mac=Command-Shift-R win=Ctrl-Shift-R linux=Ctrl-Shift-R >}} |  Insert section |
| {{< kbd mac=Option-Shift-K win=Alt-Shift-K linux=Alt-Shift-K >}} | Open global keybindings list |
| {{< kbd mac=Option-- win=Alt-- linux=Alt-- >}} | Insert left assignment operator `<-` |
