#!/usr/bin/env bash
#
# Generate static redirect stubs from _redirects into a rendered site.
#
# Netlify answers _redirects at request time. GitHub Pages serves static files
# only, so on Pages every source path needs a real file or it 404s. Every entry
# points at an external URL, so Quarto's `aliases`, which only redirects between
# pages of the same site, cannot do this. _redirects stays the single source of
# truth for the routes; this script is the only thing that knows the stub format.
#
# Runs as a Quarto post-render hook, which supplies QUARTO_PROJECT_OUTPUT_DIR:
# see the post-render entry in _quarto-positron.yml. Tested by
# scripts/test-generate-redirect-stubs.sh.
#
# Every guard below fails the render rather than skipping the rule. A skipped
# rule renders green and only surfaces later as a 404 in production.
set -euo pipefail

# Overridable so the tests can point at a fixture instead of the real file.
REDIRECTS_FILE="${REDIRECTS_FILE:-_redirects}"
OUTPUT_DIR="${QUARTO_PROJECT_OUTPUT_DIR:?QUARTO_PROJECT_OUTPUT_DIR is unset; this script runs as a Quarto post-render hook}"

# Marks a file as ours. The shadowing guard overwrites files carrying it and
# refuses to touch anything else, which is what makes reruns safe.
SENTINEL='Generated by scripts/generate-redirect-stubs.sh from _redirects. Do not edit.'

if [ ! -f "$REDIRECTS_FILE" ]; then
	echo "error: ${REDIRECTS_FILE} not found" >&2
	exit 1
fi

die() {
	echo "error: ${REDIRECTS_FILE}:${1}: ${2}" >&2
	exit 1
}

# Escaped for use in both attribute values and element text.
escape_html() {
	printf '%s' "$1" | sed -e 's/&/\&amp;/g' -e 's/</\&lt;/g' -e 's/>/\&gt;/g' -e 's/"/\&quot;/g'
}

count=0
lineno=0

while IFS= read -r line || [ -n "$line" ]; do
	lineno=$((lineno + 1))

	# Skip blank lines and whole-line comments. Deliberately not stripping a
	# trailing `#` comment: destinations legitimately contain fragments, as in
	# aws_credentials.html#amazon-bedrock-permissions.
	case "$(printf '%s' "$line" | tr -d '[:space:]')" in
		'' | '#'*) continue ;;
	esac

	read -r source_path destination extra <<<"$line"

	[ -n "$destination" ] ||
		die "$lineno" "expected '<source> <destination>', got one field: ${line}"
	[ -z "$extra" ] ||
		die "$lineno" "expected '<source> <destination>', got the extra field '${extra}': a status code or a 200 rewrite cannot be expressed as a static stub"

	case "$source_path" in
		/*) ;;
		*) die "$lineno" "source must start with '/': ${source_path}" ;;
	esac
	case "$source_path" in
		*'*'*) die "$lineno" "source contains a splat, which needs request-time matching: ${source_path}" ;;
		*:*) die "$lineno" "source contains a placeholder, which needs request-time matching: ${source_path}" ;;
		*..*) die "$lineno" "source contains '..', which would write outside ${OUTPUT_DIR}: ${source_path}" ;;
	esac
	case "$destination" in
		http://* | https://*) ;;
		*) die "$lineno" "destination must be an absolute http(s) URL for a stub to point at it: ${destination}" ;;
	esac

	rel="${source_path#/}"
	rel="${rel%/}"
	[ -n "$rel" ] || die "$lineno" "source '/' would shadow the site home page"

	# Sources map to a directory index, so both /blog and /blog/ resolve.
	target="${OUTPUT_DIR}/${rel}/index.html"

	# Shadowing guards. These check the filesystem rather than consulting
	# QUARTO_PROJECT_OUTPUT_FILES, because on an incremental render (quarto
	# preview re-rendering one page) that variable lists only what changed and
	# would miss a shadowed page. The .html sibling is checked too: Pages
	# resolves /blog to blog.html as well as to blog/index.html, so a rendered
	# blog.qmd collides with this rule even though the paths differ.
	if [ -f "$target" ] && ! grep -qF "$SENTINEL" "$target"; then
		die "$lineno" "stub for ${source_path} would shadow the rendered page ${target}"
	fi
	if [ -f "${OUTPUT_DIR}/${rel}.html" ]; then
		die "$lineno" "stub for ${source_path} conflicts with the rendered page ${OUTPUT_DIR}/${rel}.html"
	fi

	destination="$(escape_html "$destination")"
	mkdir -p "${OUTPUT_DIR}/${rel}"
	cat > "$target" <<EOF
<!DOCTYPE html>
<html lang="en">
<head>
<!-- ${SENTINEL} -->
<meta charset="utf-8">
<title>Redirecting to ${destination}</title>
<meta name="robots" content="noindex">
<meta http-equiv="refresh" content="0; url=${destination}">
<link rel="canonical" href="${destination}">
</head>
<body>
<p>Redirecting to <a href="${destination}">${destination}</a></p>
</body>
</html>
EOF
	count=$((count + 1))
done < "$REDIRECTS_FILE"

printf 'generate-redirect-stubs: wrote %d stub(s) to %s\n' "$count" "$OUTPUT_DIR"
