#!/usr/bin/env bash
#
# Fixture-based tests for generate-redirect-stubs.sh.
#
# The generator otherwise only ever runs inside a Quarto render, where a bug
# either fails a render with no test behind it to explain why or, worse, quietly
# writes a stub over a real page. Each case writes a small fixture _redirects,
# runs the script against a temp output dir, and asserts on the exit status, the
# operator-facing message, and the files produced.
#
# Run locally with: scripts/test-generate-redirect-stubs.sh
#
# Deliberately not `set -e`: most cases assert a non-zero exit.
set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
STUBS_SCRIPT="$SCRIPT_DIR/generate-redirect-stubs.sh"

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT
cd "$WORK" || exit 1

PASS=0
FAIL=0

report() {
	if [ "$2" = yes ]; then
		printf 'ok   %s\n' "$1"
		PASS=$((PASS + 1))
	else
		printf 'FAIL %s\n' "$1"
		[ -n "${3:-}" ] && printf '     %s\n' "$3"
		FAIL=$((FAIL + 1))
	fi
}

# A fresh output dir and fixture per case. Each argument becomes one line of
# _redirects, so a case reads as the file it is testing.
new_case() {
	rm -rf _site
	mkdir -p _site
	printf '%s\n' "$@" > _redirects
}

# Captures combined output in $OUT and the exit status in $STATUS.
run_stubs() {
	OUT="$(REDIRECTS_FILE="$WORK/_redirects" QUARTO_PROJECT_OUTPUT_DIR="$WORK/_site" \
		"$STUBS_SCRIPT" 2>&1)"
	STATUS=$?
}

expect_ok() {
	run_stubs
	if [ "$STATUS" -eq 0 ]; then
		report "$1" yes
	else
		report "$1" no "exited ${STATUS}: ${OUT}"
	fi
}

expect_file_contains() {
	if [ ! -f "_site/$2" ]; then
		report "$1" no "missing _site/$2"
	elif ! grep -qF "$3" "_site/$2"; then
		report "$1" no "_site/$2 lacks '$3'"
	else
		report "$1" yes
	fi
}

expect_fail() {
	run_stubs
	if [ "$STATUS" -eq 0 ]; then
		report "$1" no "expected a non-zero exit, got 0"
	elif ! printf '%s' "$OUT" | grep -qF "$2"; then
		report "$1" no "message did not mention '$2': ${OUT}"
	else
		report "$1" yes
	fi
}

expect_stub_count() {
	local found
	found="$(find _site -name index.html | wc -l | tr -d ' ')"
	if [ "$found" = "$2" ]; then
		report "$1" yes
	else
		report "$1" no "expected $2 stub(s), found ${found}"
	fi
}

# Happy path. The three rules mirror the real file: a bare source, a nested
# source with a trailing slash, and the /redirect/ convention whose destination
# carries a fragment.
new_case \
	'# Netlify redirects' \
	'' \
	'/blog  https://opensource.posit.co/blog/q/positron/' \
	'/blog/posts/2026-03-05-outgrow-your-laptop/  https://opensource.posit.co/blog/2026-03-05_outgrow-your-laptop/' \
	'/redirect/aws-bedrock-iam-permissions  https://docs.posit.co/ide/server-pro/admin/authenticating_users/aws_credentials.html#amazon-bedrock-permissions'
expect_ok "three rules render"
expect_stub_count "comments and blank lines produce no stubs" 3
expect_file_contains "bare source maps to a directory index" \
	blog/index.html 'content="0; url=https://opensource.posit.co/blog/q/positron/"'
expect_file_contains "trailing slash maps to the same directory index" \
	blog/posts/2026-03-05-outgrow-your-laptop/index.html \
	'<link rel="canonical" href="https://opensource.posit.co/blog/2026-03-05_outgrow-your-laptop/">'
expect_file_contains "a fragment in the destination survives" \
	redirect/aws-bedrock-iam-permissions/index.html '#amazon-bedrock-permissions'
expect_file_contains "stubs are noindex" \
	blog/index.html '<meta name="robots" content="noindex">'
expect_file_contains "stub offers a manual link" \
	blog/index.html '<a href="https://opensource.posit.co/blog/q/positron/">'
expect_file_contains "stub carries the sentinel" \
	blog/index.html 'Generated by scripts/generate-redirect-stubs.sh'

# Rerunning must be safe and must not churn the output: quarto preview re-runs
# the hook on every incremental render.
cp _site/blog/index.html "$WORK/first-run.html"
expect_ok "rerun over its own output"
if cmp -s "$WORK/first-run.html" _site/blog/index.html; then
	report "rerun is byte-identical" yes
else
	report "rerun is byte-identical" no "the second run changed the stub"
fi

# Destinations are HTML-escaped, or a query string would break the attribute.
new_case '/q  https://example.com/search?a=1&b=2'
expect_ok "destination with an ampersand"
expect_file_contains "ampersand is escaped" \
	q/index.html 'content="0; url=https://example.com/search?a=1&amp;b=2"'

# An empty rule set is not an error.
new_case '# only a comment'
expect_ok "comments-only _redirects"
expect_stub_count "comments-only writes nothing" 0

# Rules a static stub cannot express. Each asserts on the operator-facing
# message, so a reworded guard cannot quietly stop guarding.
new_case '/blog  https://example.com/  301!'
expect_fail "a third field" "extra field '301!'"

new_case '/blog'
expect_fail "a single field" "got one field"

new_case '/blog/*  https://example.com/'
expect_fail "a splat in the source" "splat"

new_case '/blog/:slug  https://example.com/'
expect_fail "a placeholder in the source" "placeholder"

new_case '/blog  /elsewhere/'
expect_fail "a relative destination" "absolute http(s) URL"

new_case '/blog/../etc  https://example.com/'
expect_fail "'..' in the source" "source contains '..'"

new_case 'blog  https://example.com/'
expect_fail "a source without a leading slash" "must start with '/'"

new_case '/  https://example.com/'
expect_fail "the site root as a source" "home page"

# Shadowing a real page. Both spellings matter, because Pages resolves /blog to
# either blog/index.html or blog.html.
new_case '/blog  https://example.com/'
mkdir -p _site/blog
printf '<html>a real rendered page</html>\n' > _site/blog/index.html
expect_fail "shadowing a rendered index" "would shadow the rendered page"

new_case '/blog  https://example.com/'
printf '<html>a real rendered page</html>\n' > _site/blog.html
expect_fail "conflicting with a rendered .html sibling" "conflicts with the rendered page"

# A missing rules file means something upstream broke, not "nothing to do".
new_case '/blog  https://example.com/'
rm -f _redirects
expect_fail "a missing _redirects" "not found"

# The output dir is required: run by hand outside Quarto, the script must say so
# rather than write stubs somewhere surprising.
new_case '/blog  https://example.com/'
OUT="$(REDIRECTS_FILE="$WORK/_redirects" "$STUBS_SCRIPT" 2>&1)"
STATUS=$?
if [ "$STATUS" -ne 0 ] && printf '%s' "$OUT" | grep -qF "QUARTO_PROJECT_OUTPUT_DIR"; then
	report "a missing QUARTO_PROJECT_OUTPUT_DIR" yes
else
	report "a missing QUARTO_PROJECT_OUTPUT_DIR" no "exited ${STATUS}: ${OUT}"
fi

echo
printf '%d passed, %d failed\n' "$PASS" "$FAIL"
[ "$FAIL" -eq 0 ]
