on: pull_request

name: Lint

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Check URLs in Quarto files
        uses: urlstechie/urlchecker-action@b643b43e2ac605e1475331c7b67247d242b7dce4  # v0.0.34
        with:
          file_types: .qmd
          exclude_patterns: https://cdn.posit.co/positron/prereleases/,https://positron.posit.co/images/,https://github.com/posit-dev/positron/issues
          retry_count: 3

      - name: Check URLs in _redirects
        uses: urlstechie/urlchecker-action@b643b43e2ac605e1475331c7b67247d242b7dce4  # v0.0.34
        with:
          include_files: _redirects
          file_types: _redirects
          retry_count: 3
