on:
  workflow_dispatch:
    inputs:
      release_channel:
        description: 'Release channel to publish to (e.g., "releases", "dailies", "staging")'
        required: true
        default: 'releases'
        type: string

name: Publish Release Notes

jobs:
  s3-release-notes:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials for S3
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_S3_RW_ROLE }}
          aws-region: us-east-1

      - name: Get Next Release Version
        id: get-next-release
        run: |
          NEXT_RELEASE=$(grep '^NEXT_RELEASE=' $GITHUB_WORKSPACE/_environment | cut -d '=' -f 2 | tr -d '"')
          echo "next_release=${NEXT_RELEASE}" >> $GITHUB_ENV

      - name: Upload Release Notes to S3
        run: |
          S3_PREFIX="s3://posit-positron-downloads/positron/${{ inputs.release_channel}}"
          aws s3 cp "${GITHUB_WORKSPACE}/release-notes/next.md" "${S3_PREFIX}/release-notes/release-${{ steps.get-next-release.outputs.next_release }}.md" --no-progress

      - name: Configure AWS Credentials for CloudFront
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_CDN_RW_ROLE }}
          aws-region: us-east-1

      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.AWS_CDN_DISTRIBUTION_ID }} \
            --paths \
              "/positron/releases/release-notes/*" \
